name: Build the Project

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: Release      

    steps:
    - name: View Files
      run: ls -a

    - name: Checkout
      uses: actions/checkout@v4

    - run: ls -a
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Dependencies
      run: dotnet restore
   
    - name: Build 
      run: dotnet build --configuration $BUILD_CONFIG --no-restore