name: Demo Workflow

on: 
    push:

jobs:
    hello:
        name: Say Hello
        runs-on: ubuntu-latest
        steps: 
            - run: echo hello! this is a demo
    checkout:
        name: Checkout Code
        runs-on: ubuntu-latest
        steps:
            - run: ls
            - uses: actions/checkout@v4
            - run: ls

        

