name: Demo Workflow

on: 
    push:
        branches: [main]

jobs: 
    hello:
        name: Hello!
        runs-on: ubuntu-latest
        steps: 
            - name: Say Hello
              run: echo hello!!!
        
